### ISSUE TITLE
Card ease not synced

### ISSUE THREAD

**Issue by zebala** [AnKingMed/Reset-Ease#3]
The add-on does not seem to mark the cards for sync, so the ease change is not uploaded to AnkiWeb. Realized this when looking the cards with AnkiMobile. Workaround is to manually do something with all the cards, but it gets a bit tedious. Not sure if just flagging all the cards temporarily forces a full sync of the card.

**Comment by AnKingMed** [comment]
Have you tried force syncing after using the add-on?  In preferences under syncing there is a checkbox to force sync on next next. Please let me know if that fixes it

**Comment by cyphar** [comment]
This add-on should use the higher-level Anki hooks to update the database (which allows Anki to mark the cards as "changed" internally) -- this would allow Anki to do a graceful sync (rather than getting users to forcefully synchronise things). I can send a patch for this in a little bit. The simplest solution would be to set `usn = -1` but that's not as great.

[There's a forum thread about this issue.](https://forums.ankiweb.net/t/card-ease-not-syncing/3570)

**Comment by AnKingMed** [comment]
@cyphar That'd be much appreciated. I haven't had time to pay attention much to the new anki hooks or put significant time into updating add-ons

**Comment by zebala** [comment]
#4 worked correctly for me!

On another small note, the manifest.json version should probably be udpated to Anki version 2.1, since manual install fails otherwise.

Thank you again for the quick responses, especially @cyphar for the fix!

**Comment by cyphar** [comment]
Based on my tests, manual install works fine even with the `manifest.json` containing a `version` value of `2.0`.

**Comment by zebala** [comment]
Interesting. For me "Install from file" in and selecting the `.ankiaddon` file Anki complained about an invalid `manifest.json`. On macOS anki 2.1.33.

**Comment by cyphar** [comment]
Ah sorry, I just copied the add-on folder directly into `addons21` -- I forgot you can actually install it as well. The addon-docs are kinda light on what a valid `manifest.json` should look like.
